version: '3.8'
services:
  nginx:
    container_name: testnginx
    image: nginx:latest
    ports:
      - "80:80"
    volumes:
      - ./nginx/default.conf:/etc/nginx/conf.d/default.conf
      - ./src:/var/www/html
    depends_on:
      - php
    networks:
      - app-network

  php:
    container_name: testphp
    build:
      context: ./php
    volumes:
      - ./src:/var/www/html
    expose:
      - "9000"
    networks:
      - app-network

  mysql:
    container_name: testmysql
    image: mariadb:10.5
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - ./.docker/mysql/data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
        driver: bridge